spring:

  web:
    cors
  application:
    name: LightCrewAdmin

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server:
  port: 8088
  error:
    include-message: always
    include-binding-errors: always



cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# Logging
#logging:
#  level:
#    az.lightcrew: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE