spring:
  application:
    name: user-ms

  datasource:
    url: jdbc:postgresql://localhost:5434/
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    analytics-enabled: false
