server:
  port: 8020

spring:
  application:
    name: Api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/authServiceFallback
            - RewritePath=/api/v1/users/(?<segment>.*), /api/v1/users/${segment}


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true


