version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: lightcrew_db_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lightcrew_db
    volumes:
      - lightcrew_data:/var/lib/postgresql/data
    networks:
      - lightcrew_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  lightcrew_network:

volumes:
  lightcrew_data: